### ISSUE TITLE
Public availability

### ISSUE THREAD

**Issue by bielok** [Gals42/LLk-Parsing-Table-Generator#1]
Hello! Is there a publicly available instance of the written work?

Kind regards.

**Comment by rkocman** [comment]
Hello. Regarding the written sources:

 - Aho, A.V., Ullman, J.D.: The Theory of Parsing, Translation, and Compiling, Volume I: Parsing.
This is a well-known book although quite old; it should be still easy to find it online.

- Kolář, D.: Simulation of LLk Parsers with Wide Context by Automaton with One-Symbol Reading Head.
This paper is more problematic. I cannot find a publicly available source at the moment. But you can try ask the original author:
https://www.fit.vut.cz/person/kolar/.en
